// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Class struct {
	Name        string
	ProgramCode string
	Year        int32
	StudyType   string
	Active      bool
}

type Student struct {
	Uid       string
	FirstName string
	LastName  string
	Email     string
	Active    bool
	ClassName string
}
