name: CD

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          TAGS="ghcr.io/${{ github.repository }}:development"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS="$TAGS,ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tags }}

